In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
independant=dataset[["age","bmi","children","sex_male","smoker_yes"]]
dependant=dataset[["charges"]]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['friedman_mse','absolute_error','poisson','squared_error'],'max_features':['sqrt','log2'],'splitter':['random','best']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'poisson', 'squared_error'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['random', 'best']},
             verbose=3)

In [7]:
result=grid.cv_results_

In [8]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008500,0.002907,0.002629,0.000200,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.701896,0.462864,0.589753,0.610398,0.597722,0.592527,0.076326,12
1,0.005280,0.000295,0.002839,0.000164,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.593453,0.664615,0.641076,0.577615,0.661746,0.627701,0.035727,4
2,0.004149,0.001184,0.002280,0.000105,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.754719,0.605466,0.608106,0.490479,0.605764,0.612907,0.083939,7
3,0.004170,0.000368,0.002322,0.000277,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.688705,0.603761,0.421771,0.461783,0.529755,0.541155,0.096305,14
4,0.010337,0.001455,0.002351,0.000156,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.719712,0.651351,0.607041,0.619918,0.621906,0.643985,0.040547,3
5,0.012731,0.002504,0.002523,0.000550,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.721831,0.582433,0.619469,0.706936,0.630744,0.652283,0.053374,1
6,0.010096,0.000842,0.002186,0.000253,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.428361,0.646974,0.577663,0.401518,0.595225,0.529948,0.097002,16
7,0.012706,0.001797,0.002448,0.000274,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.652376,0.655907,0.564463,0.478437,0.682116,0.606660,0.075406,8
8,0.004014,0.000601,0.002569,0.000379,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.572378,0.508317,0.502280,0.532372,0.586815,0.540432,0.033834,15
9,0.004425,0.000229,0.002285,0.000201,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.408476,0.496585,0.655381,0.611347,0.656419,0.565642,0.097829,13
10,0.003534,0.000162,0.002203,0.000115,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.618212,0.479753,0.734392,0.592883,0.590844,0.603217,0.081160,10
11,0.004007,0.000342,0.002228,0.000312,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.705873,0.614367,0.746632,0.612588,0.570089,0.649910,0.065597,2
12,0.003347,0.000081,0.002103,0.000106,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.772388,0.547345,0.538643,0.633840,0.616315,0.621706,0.084036,5
13,0.003846,0.000111,0.002145,0.000092,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.723576,0.664017,0.669769,0.674136,0.271405,0.600581,0.165955,11
14,0.003482,0.000444,0.002146,0.000079,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.635770,0.570164,0.654031,0.564988,0.603716,0.605734,0.035112,9
15,0.003602,0.000371,0.001794,0.000144,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.764442,0.415447,0.659674,0.622127,0.628086,0.617955,0.113427,6

In [9]:
age=float(input("Age"))
bmi=float(input("BMI"))
child=float(input("Children"))
male=float(input("Male or Female ( 0 or 1)"))
smoke=float(input("Smoker yes or no ( 0 or 1)"))

Age 19
BMI 27.9
Children 0
Male or Female ( 0 or 1) 0
Smoker yes or no ( 0 or 1) 1

In [10]:
future_prediction=grid.predict([[age,bmi,child,male,smoke]])

In [11]:
future_prediction

array([58571.07448])