In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
independant=dataset[["age","bmi","children","sex_male","smoker_yes"]]
dependant=dataset[["charges"]]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['friedman_mse','absolute_error','poisson','squared_error'],'max_features':['sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'poisson', 'squared_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [8]:
result=grid.cv_results_

In [9]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.035938,0.001175,0.005256,0.000584,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.838942,0.785276,0.777100,0.817444,0.772140,0.798180,0.025774,10
1,0.299603,0.028880,0.022924,0.005591,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863237,0.788745,0.812562,0.826419,0.772279,0.812648,0.031464,3
2,0.037817,0.002885,0.004862,0.000895,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.868243,0.779048,0.790775,0.770431,0.747447,0.791189,0.041059,14
3,0.300643,0.013322,0.020599,0.000792,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.868390,0.793446,0.806219,0.824296,0.773727,0.813216,0.032144,2
4,0.093267,0.013489,0.004633,0.000447,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.846641,0.778053,0.790713,0.799220,0.777303,0.798386,0.025480,9
5,0.809069,0.079569,0.019571,0.001881,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.858034,0.787379,0.809681,0.831848,0.774641,0.812317,0.030066,4
6,0.090309,0.007650,0.004238,0.000621,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.823234,0.780723,0.795634,0.809547,0.756432,0.793114,0.023163,13
7,0.798201,0.097972,0.020816,0.001702,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859484,0.788866,0.810053,0.824421,0.770212,0.810607,0.030609,7
8,0.034251,0.002218,0.003778,0.000065,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.842235,0.771364,0.804672,0.810182,0.749302,0.795551,0.032251,12
9,0.417988,0.065462,0.021749,0.001712,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.866096,0.790516,0.805989,0.833130,0.771483,0.813443,0.033172,1
10,0.043877,0.002329,0.005894,0.001663,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.842539,0.769106,0.799102,0.804450,0.770445,0.797129,0.026896,11
11,0.382889,0.039894,0.020779,0.001696,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.856891,0.787520,0.811152,0.829375,0.770185,0.811025,0.030532,6
12,0.076159,0.047214,0.007612,0.003690,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.841853,0.753413,0.772359,0.783668,0.749975,0.780254,0.033184,16
13,0.318165,0.015043,0.017791,0.002583,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.868764,0.791582,0.805834,0.823412,0.771027,0.812124,0.033124,5
14,0.051421,0.014091,0.005340,0.001071,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.839361,0.748576,0.786815,0.817572,0.746189,0.787703,0.036921,15
15,0.243810,0.008911,0.013316,0.002028,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.866500,0.789345,0.800942,0.819471,0.761837,0.807619,0.034877,8

In [10]:
age=float(input("Age"))
bmi=float(input("BMI"))
child=float(input("Children"))
male=float(input("Male or Female ( 0 or 1)"))
smoke=float(input("Smoker yes or no ( 0 or 1)"))

Age 19
BMI 27.9
Children 0
Male or Female ( 0 or 1) 0
Smoker yes or no ( 0 or 1) 1

In [11]:
future_prediction=grid.predict([[age,bmi,child,male,smoke]])
future_prediction

array([49849.2503695])