In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
independant=dataset[["age","bmi","children","sex_male","smoker_yes"]]
dependant=dataset[["charges"]]

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['friedman_mse','absolute_error','poisson','squared_error'],'max_features':['sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independant,independant)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'poisson', 'squared_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [6]:
result=grid.cv_results_

In [7]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.044071,0.003541,0.006884,0.000702,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.915221,0.904125,0.897581,0.900636,0.921486,0.907810,0.009073,7
1,0.365811,0.012778,0.025067,0.001947,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.932918,0.932952,0.918779,0.920357,0.928320,0.926665,0.006055,2
2,0.041610,0.004148,0.006292,0.000526,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.895082,0.898758,0.885066,0.899114,0.861379,0.887880,0.014189,8
3,0.378692,0.011105,0.023102,0.001634,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.929929,0.923882,0.938510,0.929311,0.918707,0.928068,0.006621,1
4,0.351382,0.010976,0.005511,0.000127,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.846844,0.878790,0.857018,0.870135,0.892143,0.868986,0.015920,11
5,3.563603,0.129032,0.023074,0.001067,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.912923,0.917670,0.907359,0.902692,0.912555,0.910640,0.005143,6
6,0.352776,0.014565,0.005486,0.000359,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.854854,0.867594,0.880140,0.848863,0.863213,0.862933,0.010781,12
7,3.627818,0.106616,0.021415,0.002187,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.919695,0.912873,0.912093,0.900859,0.910910,0.911286,0.006046,4
8,0.049867,0.015775,0.007018,0.003045,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.458761,0.447752,0.489242,0.425623,0.457188,0.455713,0.020516,15
9,0.330261,0.037877,0.019726,0.001942,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.480462,0.472035,0.464237,0.473143,0.479475,0.473871,0.005858,13
10,0.028804,0.001988,0.004911,0.000398,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.407068,0.365842,0.465900,0.365657,0.457477,0.412389,0.043070,16
11,0.313198,0.051008,0.022284,0.005934,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.475722,0.472571,0.454519,0.472845,0.464943,0.468120,0.007681,14
12,0.063830,0.016862,0.021177,0.023578,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.864115,0.877910,0.853647,0.907862,0.874071,0.875521,0.018234,9
13,0.394721,0.027545,0.025349,0.004841,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.907941,0.925117,0.908019,0.910610,0.902760,0.910889,0.007556,5
14,0.045771,0.007559,0.005914,0.000350,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.887043,0.862379,0.886517,0.861123,0.862300,0.871872,0.012181,10
15,0.349511,0.011730,0.020425,0.001539,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.914878,0.917627,0.913773,0.914096,0.904719,0.913019,0.004366,3

In [8]:
age=float(input("Age"))
bmi=float(input("BMI"))
child=float(input("Children"))
male=float(input("Male or Female ( 0 or 1)"))
smoke=float(input("Smoker yes or no ( 0 or 1)"))

Age 19
BMI 27.9
Children 0
Male or Female ( 0 or 1) 0
Smoker yes or no ( 0 or 1) 1

In [9]:
future_prediction=grid.predict([[age,bmi,child,male,smoke]])
future_prediction

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([[1.96100e+01, 2.79992e+01, 1.00000e-02, 1.00000e-02, 9.70000e-01]])