In [39]:
import pandas as pd
dataset=pd.read_csv("C:\AI\Artificial-Intelligence\Machine Learning\Assignment_MachineLearning\insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [40]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [41]:
independant=dataset[["age","bmi","children","sex_male","smoker_yes"]]
dependant=dataset[["charges"]]

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [43]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [44]:
stdy=StandardScaler()
Y_train=stdy.fit_transform(Y_train)
Y_test=stdy.transform(Y_test)

In [45]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(X_train,Y_train)

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [46]:
Y_pred=regressor.predict(X_test)

In [47]:
from sklearn.metrics import r2_score
rscore=r2_score(Y_test,Y_pred)
rscore

0.8158353481270291

In [48]:
import pickle
pickle.dump(regressor,open('Final_preprocessesInput&Output_SVR.sav','wb'))

In [49]:
preinput=std.transform([[19,27.9,0,1,0]])
preinput

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.46169465, -0.45767803, -0.89833872,  1.02378711, -0.50466988]])

In [50]:
model=pickle.load(open('Final_preprocessesInput&Output_SVR.sav','rb'))
result=model.predict(preinput)
result

array([-0.90891573])

In [51]:
preoutput=stdy.inverse_transform([result])
preoutput

array([[2440.66709707]])