In [1]:
import pandas as pd
dt=pd.read_csv('C:\AI\Artificial-Intelligence\Machine Learning\Classification\Social_Network_Ads.csv')
dt

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
dt=pd.get_dummies(dt,dtype=int,drop_first=True)
dt

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [3]:
dt=dt.drop('User ID',axis=1)
dt

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [4]:
ip=dt[['Age','EstimatedSalary','Gender_Male']]
op=dt['Purchased']

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,test_size=0.30,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [12]:
grid_parm={'n_estimators':[100],'criterion':['gini','entropy','log_loss'],'max_features':['sqrt','log2']}
grid_model=GridSearchCV(RandomForestClassifier(),grid_parm,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid_model.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [100]},
             scoring='f1_weighted', verbose=3)

In [13]:
result=grid_model.cv_results_

In [14]:
grid_pred=grid_model.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
print(cm)

[[74  5]
 [ 5 36]]

In [16]:
from sklearn.metrics import classification_report
classy=classification_report(y_test,grid_pred)
print(classy)

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        79
           1       0.88      0.88      0.88        41

    accuracy                           0.92       120
   macro avg       0.91      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120

In [17]:
from sklearn.metrics import roc_auc_score # r-receiver, o-operating, c- curve | a-area, u- under, c-curve
roc_auc_score(y_test,grid_model.predict_proba(x_test)[:,1])

np.float64(0.9620253164556962)

In [18]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.375910,0.020408,0.024558,0.002400,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.874254,0.857143,0.841398,0.911105,0.964286,0.889637,0.043938,1
1,0.329004,0.057700,0.025087,0.002436,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.874254,0.840114,0.841398,0.929144,0.946153,0.886213,0.044074,4
2,0.340600,0.034603,0.020864,0.000463,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.874254,0.840114,0.841398,0.911105,0.946153,0.882605,0.041046,5
3,0.316473,0.025369,0.021669,0.001308,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.874254,0.875644,0.841398,0.911105,0.945469,0.889574,0.035602,2
4,0.315663,0.033193,0.021550,0.002066,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.874254,0.840114,0.823129,0.911105,0.909115,0.871543,0.035541,6
5,0.249643,0.007172,0.018695,0.001726,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",0.874254,0.857143,0.859435,0.911105,0.945469,0.889481,0.034008,3