In [1]:
import pandas as pd

In [3]:
dt=pd.read_csv('C:\AI\Artificial-Intelligence\Machine Learning\Classification\Social_Network_Ads.csv')
dt

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dt=pd.get_dummies(dt,dtype=int,drop_first=True)
dt

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dt=dt.drop('User ID',axis=1)
dt

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [7]:
ip=dt[['Age','EstimatedSalary','Gender_Male']]
op=dt['Purchased']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [12]:
param_grid={'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],'penalty':['l1', 'l2', 'elasticnet']}
grid_model=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
grid_model.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 3/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 4/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 5/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 1/5] END ......penalty=l1, solver=liblinear;, score=0.836 total time=   0.0s
[CV 2/5] END ......penalty=l1, solver=liblinear;, score=0.802 total time=   0.0s
[CV 3/5] END ......penalty=l1, solver=liblinear;, score=0.645 total time=   0.0s
[CV 4/5] END ......penalty=l1, solver=liblinear;, score=0.928 total time=   0.0s
[CV 5/5] END ......penalty=l1, solver=liblinear;, score=0.909 total time=   0.0s
[CV 1/5] END ........penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 2/5] END ........penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 3/5] END ........penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 4/5] END ........penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 5/5] END ........penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 1/5] END ..penalty=l1, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 2/5] END ..penalty=l1, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 3/5] END ..penalty=l1, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 4/5] END ..penalty=l1, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 5/5] END ..penalty=l1, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 1/5] END ..............penalty=l1, solver=sag;, score=nan total time=   0.0s
[CV 2/5] END ..............penalty=l1, solver=sag;, score=nan total time=   0.0s
[CV 3/5] END ..............penalty=l1, solver=sag;, score=nan total time=   0.0s
[CV 4/5] END ..............penalty=l1, solver=sag;, score=nan total time=   0.0s
[CV 5/5] END ..............penalty=l1, solver=sag;, score=nan total time=   0.0s
[CV 1/5] END ...........penalty=l1, solver=saga;, score=0.836 total time=   0.0s
[CV 2/5] END ...........penalty=l1, solver=saga;, score=0.802 total time=   0.0s
[CV 3/5] END ...........penalty=l1, solver=saga;, score=0.645 total time=   0.0s
[CV 4/5] END ...........penalty=l1, solver=saga;, score=0.928 total time=   0.0s
[CV 5/5] END ...........penalty=l1, solver=saga;, score=0.909 total time=   0.0s
[CV 1/5] END ..........penalty=l2, solver=lbfgs;, score=0.836 total time=   0.0s
[CV 2/5] END ..........penalty=l2, solver=lbfgs;, score=0.802 total time=   0.0s
[CV 3/5] END ..........penalty=l2, solver=lbfgs;, score=0.645 total time=   0.0s
[CV 4/5] END ..........penalty=l2, solver=lbfgs;, score=0.928 total time=   0.0s
[CV 5/5] END ..........penalty=l2, solver=lbfgs;, score=0.890 total time=   0.0s
[CV 1/5] END ......penalty=l2, solver=liblinear;, score=0.836 total time=   0.0s
[CV 2/5] END ......penalty=l2, solver=liblinear;, score=0.802 total time=   0.0s
[CV 3/5] END ......penalty=l2, solver=liblinear;, score=0.645 total time=   0.0s
[CV 4/5] END ......penalty=l2, solver=liblinear;, score=0.928 total time=   0.0s
[CV 5/5] END ......penalty=l2, solver=liblinear;, score=0.890 total time=   0.0s
[CV 1/5] END ......penalty=l2, solver=newton-cg;, score=0.836 total time=   0.0s
[CV 2/5] END ......penalty=l2, solver=newton-cg;, score=0.802 total time=   0.0s
[CV 3/5] END ......penalty=l2, solver=newton-cg;, score=0.645 total time=   0.0s
[CV 4/5] END ......penalty=l2, solver=newton-cg;, score=0.928 total time=   0.0s
[CV 5/5] END ......penalty=l2, solver=newton-cg;, score=0.890 total time=   0.0s
[CV 1/5] END penalty=l2, solver=newton-cholesky;, score=0.836 total time=   0.0s
[CV 2/5] END penalty=l2, solver=newton-cholesky;, score=0.802 total time=   0.0s
[CV 3/5] END penalty=l2, solver=newton-cholesky;, score=0.645 total time=   0.0s
[CV 4/5] END penalty=l2, solver=newton-cholesky;, score=0.928 total time=   0.0s
[CV 5/5] END penalty=l2, solver=newton-cholesky;, score=0.890 total time=   0.0s
[CV 1/5] END ............penalty=l2, solver=sag;, score=0.836 total time=   0.0s
[CV 2/5] END ............penalty=l2, solver=sag;, score=0.802 total time=   0.0s
[CV 3/5] END ............penalty=l2, solver=sag;, score=0.645 total time=   0.0s
[CV 4/5] END ............penalty=l2, solver=sag;, score=0.928 total time=   0.0s
[CV 5/5] END ............penalty=l2, solver=sag;, score=0.890 total time=   0.0s
[CV 1/5] END ...........penalty=l2, solver=saga;, score=0.836 total time=   0.0s
[CV 2/5] END ...........penalty=l2, solver=saga;, score=0.802 total time=   0.0s
[CV 3/5] END ...........penalty=l2, solver=saga;, score=0.645 total time=   0.0s
[CV 4/5] END ...........penalty=l2, solver=saga;, score=0.928 total time=   0.0s
[CV 5/5] END ...........penalty=l2, solver=saga;, score=0.890 total time=   0.0s
[CV 1/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 3/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 4/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 5/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 1/5] END penalty=elasticnet, solver=liblinear;, score=nan total time=   0.0s
[CV 2/5] END penalty=elasticnet, solver=liblinear;, score=nan total time=   0.0s
[CV 3/5] END penalty=elasticnet, solver=liblinear;, score=nan total time=   0.0s
[CV 4/5] END penalty=elasticnet, solver=liblinear;, score=nan total time=   0.0s
[CV 5/5] END penalty=elasticnet, solver=liblinear;, score=nan total time=   0.0s
[CV 1/5] END penalty=elasticnet, solver=newton-cg;, score=nan total time=   0.0s
[CV 2/5] END penalty=elasticnet, solver=newton-cg;, score=nan total time=   0.0s
[CV 3/5] END penalty=elasticnet, solver=newton-cg;, score=nan total time=   0.0s
[CV 4/5] END penalty=elasticnet, solver=newton-cg;, score=nan total time=   0.0s
[CV 5/5] END penalty=elasticnet, solver=newton-cg;, score=nan total time=   0.0s
[CV 1/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 2/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 3/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 4/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 5/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 1/5] END ......penalty=elasticnet, solver=sag;, score=nan total time=   0.0s
[CV 2/5] END ......penalty=elasticnet, solver=sag;, score=nan total time=   0.0s
[CV 3/5] END ......penalty=elasticnet, solver=sag;, score=nan total time=   0.0s
[CV 4/5] END ......penalty=elasticnet, solver=sag;, score=nan total time=   0.0s
[CV 5/5] END ......penalty=elasticnet, solver=sag;, score=nan total time=   0.0s
[CV 1/5] END .....penalty=elasticnet, solver=saga;, score=nan total time=   0.0s
[CV 2/5] END .....penalty=elasticnet, solver=saga;, score=nan total time=   0.0s
[CV 3/5] END .....penalty=elasticnet, solver=saga;, score=nan total time=   0.0s
[CV 4/5] END .....penalty=elasticnet, solver=saga;, score=nan total time=   0.0s
[CV 5/5] END .....penalty=elasticnet, solver=saga;, score=nan total time=   0.0s

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
50 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 71, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 63, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1203, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.823975          nan        nan        nan 0.823975
 0.82017479 0.82017479 0.82017479 0.82017479 0.82017479 0.82017479
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(), n_jobs=1,
             param_grid={'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [13]:
result=grid_model.cv_results_

In [14]:
grid_pred=grid_model.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
print(cm)

[[74  5]
 [ 8 33]]

In [16]:
from sklearn.metrics import classification_report
classy=classification_report(y_test,grid_pred)
print(classy)

              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

In [17]:
from sklearn.metrics import roc_auc_score # r-receiver, o-operating, c- curve | a-area, u- under, c-curve
roc_auc_score(y_test,grid_model.predict_proba(x_test)[:,1])

np.float64(0.9493670886075949)

In [18]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001085,0.000363,0.000000,0.000000,l1,lbfgs,"{'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.002068,0.000544,0.004399,0.001038,l1,liblinear,"{'penalty': 'l1', 'solver': 'liblinear'}",0.835985,0.802399,0.644599,0.927778,0.909115,0.823975,0.100806,1
2,0.001238,0.000345,0.000000,0.000000,l1,newton-cg,"{'penalty': 'l1', 'solver': 'newton-cg'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,0.000636,0.000120,0.000000,0.000000,l1,newton-cholesky,"{'penalty': 'l1', 'solver': 'newton-cholesky'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
4,0.000638,0.000167,0.000000,0.000000,l1,sag,"{'penalty': 'l1', 'solver': 'sag'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
5,0.001567,0.000222,0.002387,0.000137,l1,saga,"{'penalty': 'l1', 'solver': 'saga'}",0.835985,0.802399,0.644599,0.927778,0.909115,0.823975,0.100806,1
6,0.005361,0.005528,0.002949,0.000178,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
7,0.001414,0.000086,0.002893,0.000163,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
8,0.005252,0.001003,0.013120,0.018060,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
9,0.012363,0.011713,0.004371,0.000430,l2,newton-cholesky,"{'penalty': 'l2', 'solver': 'newton-cholesky'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
10,0.002586,0.000521,0.003883,0.000865,l2,sag,"{'penalty': 'l2', 'solver': 'sag'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
11,0.002262,0.000237,0.003683,0.000231,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.835985,0.802399,0.644599,0.927778,0.890114,0.820175,0.097839,3
12,0.000898,0.000074,0.000000,0.000000,elasticnet,lbfgs,"{'penalty': 'elasticnet', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
13,0.000760,0.000071,0.000000,0.000000,elasticnet,liblinear,"{'penalty': 'elasticnet', 'solver': 'liblinear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
14,0.000788,0.000022,0.000000,0.000000,elasticnet,newton-cg,"{'penalty': 'elasticnet', 'solver': 'newton-cg'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
15,0.000774,0.000012,0.000000,0.000000,elasticnet,newton-cholesky,"{'penalty': 'elasticnet', 'solver': 'newton-ch...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
16,0.000630,0.000035,0.000000,0.000000,elasticnet,sag,"{'penalty': 'elasticnet', 'solver': 'sag'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
17,0.000833,0.000283,0.000000,0.000000,elasticnet,saga,"{'penalty': 'elasticnet', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9