In [1]:
import pandas as pd
dt=pd.read_csv('C:\AI\Artificial-Intelligence\Machine Learning\Classification\Social_Network_Ads.csv')
dt

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
dt=pd.get_dummies(dt,dtype=int,drop_first=True)
dt

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [3]:
dt=dt.drop('User ID',axis=1)
dt

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [4]:
ip=dt[['Age','EstimatedSalary','Gender_Male']]
op=dt['Purchased']

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,test_size=0.30,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [8]:
grid_parm={'splitter':['best','random'],'criterion':['gini','entropy','log_loss'],'max_features':['sqrt','log2']}
grid_model=GridSearchCV(DecisionTreeClassifier(),grid_parm,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid_model.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [9]:
result=grid_model.cv_results_

In [10]:
grid_pred=grid_model.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
print(cm)

[[73  6]
 [ 9 32]]

In [12]:
from sklearn.metrics import classification_report
classy=classification_report(y_test,grid_pred)
print(classy)

              precision    recall  f1-score   support

           0       0.89      0.92      0.91        79
           1       0.84      0.78      0.81        41

    accuracy                           0.88       120
   macro avg       0.87      0.85      0.86       120
weighted avg       0.87      0.88      0.87       120

In [13]:
from sklearn.metrics import roc_auc_score # r-receiver, o-operating, c- curve | a-area, u- under, c-curve
roc_auc_score(y_test,grid_model.predict_proba(x_test)[:,1])

np.float64(0.8522692188947206)

In [14]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003785,0.000188,0.006220,0.000477,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.819142,0.785714,0.807155,0.841045,0.910254,0.832662,0.042728,7
1,0.003978,0.000348,0.006214,0.000636,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.872432,0.872432,0.789152,0.874356,0.816856,0.845046,0.035434,2
2,0.003355,0.000529,0.005621,0.000977,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.812540,0.799537,0.823129,0.872761,0.910254,0.843644,0.041517,3
3,0.002712,0.000103,0.005410,0.000386,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.763089,0.857143,0.787755,0.874356,0.819444,0.820357,0.041503,11
4,0.003126,0.000315,0.005367,0.000442,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.816207,0.766471,0.789152,0.768874,0.909115,0.809964,0.052693,12
5,0.002920,0.000382,0.005208,0.000647,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.875644,0.799537,0.789152,0.753294,0.926743,0.828874,0.063114,10
6,0.002853,0.000358,0.005012,0.000199,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.852966,0.799537,0.807155,0.841045,0.850877,0.830316,0.022515,9
7,0.002878,0.000446,0.004971,0.000275,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.840114,0.766471,0.823129,0.892857,0.872761,0.839066,0.043713,4
8,0.002893,0.000378,0.004995,0.000575,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.835985,0.840114,0.841398,0.859025,0.809578,0.837220,0.015918,6
9,0.002436,0.000237,0.005023,0.000351,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.838326,0.802399,0.841398,0.839990,0.872761,0.838975,0.022301,5
10,0.002670,0.000052,0.005301,0.000531,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.838326,0.804584,0.804584,0.858289,0.853485,0.831853,0.023220,8
11,0.002515,0.000098,0.004294,0.000327,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.833024,0.855314,0.824293,0.859025,0.874356,0.849202,0.018159,1