In [1]:
import pandas as pd
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [3]:
dataset=dataset.drop('User ID',axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [4]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [5]:
independant=dataset[['Age','EstimatedSalary','Gender_Male']]
dependant=dataset['Purchased']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [11]:
#https://scikit-learn.org/stable/modules/naive_bayes.html
from sklearn.naive_bayes import GaussianNB
gn=GaussianNB()
gn.fit(X_train,Y_train)
Y_pred=gn.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

from sklearn.metrics import classification_report
classy=classification_report(Y_test,Y_pred)
print(classy)

[[74  5]
 [ 8 33]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

In [13]:
#https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB
from sklearn.naive_bayes import MultinomialNB
mul=MultinomialNB()
mul.fit(X_train,Y_train)
Y_pred=mul.predict(X_test)

from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(Y_test,Y_pred)
print(cm1)

from sklearn.metrics import classification_report
classy1=classification_report(Y_test,Y_pred)
print(classy1)

[[68 11]
 [28 13]]
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

In [14]:
#https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.ComplementNB.html#sklearn.naive_bayes.ComplementNB
from sklearn.naive_bayes import ComplementNB
com=ComplementNB()
com.fit(X_train,Y_train)
Y_pred=com.predict(X_test)

from sklearn.metrics import confusion_matrix
cm2=confusion_matrix(Y_test,Y_pred)
print(cm2)

from sklearn.metrics import classification_report
classy2=classification_report(Y_test,Y_pred)
print(classy2)

[[42 37]
 [20 21]]
              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

In [15]:
#https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB
from sklearn.naive_bayes import BernoulliNB
br=BernoulliNB()
br.fit(X_train,Y_train)
Y_pred=br.predict(X_test)

from sklearn.metrics import confusion_matrix
cm3=confusion_matrix(Y_test,Y_pred)
print(cm3)

from sklearn.metrics import classification_report
classy3=classification_report(Y_test,Y_pred)
print(classy3)

[[79  0]
 [41  0]]
              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ragap\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
#https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html#sklearn.naive_bayes.CategoricalNB
from sklearn.naive_bayes import CategoricalNB
cat=CategoricalNB()
cat.fit(X_train,Y_train)
Y_pred=cat.predict(X_test)

from sklearn.metrics import confusion_matrix
cm4=confusion_matrix(Y_test,Y_pred)
print(cm4)

from sklearn.metrics import classification_report
classy4=classification_report(Y_test,Y_pred)
print(classy4)

[[76  3]
 [ 9 32]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120